from __future__ import annotations

import argparse
import keyword
import re
from datetime import date
from pathlib import Path


SKIP_DIRS = {".git", ".agents", ".codex", "__pycache__", "companies", "study"}

DIFFICULTIES = ("Easy", "Medium", "Hard")

INDEX_START = "<!-- INDEX:START (auto-generated by create_solution.py; do not edit by hand) -->"
INDEX_END = "<!-- INDEX:END -->"


def to_kebab_case(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower())
    return slug.strip("-")


def topic_folders(root: Path) -> list[Path]:
    return sorted(
        path
        for path in root.iterdir()
        if path.is_dir() and path.name not in SKIP_DIRS
    )


def choose_folder(folders: list[Path]) -> Path:
    print("Choose a folder:")
    for index, folder in enumerate(folders, start=1):
        print(f"{index}. {folder.name}")

    while True:
        choice = input("Folder number or name: ").strip()
        if not choice:
            print("Please enter a folder number or name.")
            continue

        if choice.isdigit():
            index = int(choice)
            if 1 <= index <= len(folders):
                return folders[index - 1]

        for folder in folders:
            if folder.name == choice:
                return folder

        print("Folder not found. Try again.")


def ask_method_name() -> str:
    while True:
        method_name = input("Solution method name: ").strip()
        if method_name.isidentifier() and not keyword.iskeyword(method_name):
            return method_name
        print("Use a valid Python method name, like twoSum or combinationSum.")


def ask_problem_number() -> str:
    while True:
        problem_number = input("LeetCode problem number: ").strip()
        if problem_number.isdigit() and int(problem_number) > 0:
            return str(int(problem_number))
        print("Use a positive problem number, like 39.")


def ask_problem_title() -> tuple[str, str]:
    while True:
        problem_title = input("Problem title: ").strip()
        slug = to_kebab_case(problem_title)
        if slug:
            return problem_title, slug
        print("Use a problem title, like Combination Sum.")


def ask_difficulty() -> str:
    options = " / ".join(f"{i}={d}" for i, d in enumerate(DIFFICULTIES, start=1))
    while True:
        choice = input(f"Difficulty ({options}): ").strip()
        if choice.isdigit() and 1 <= int(choice) <= len(DIFFICULTIES):
            return DIFFICULTIES[int(choice) - 1]
        for difficulty in DIFFICULTIES:
            if choice.lower() == difficulty.lower():
                return difficulty
        print("Pick Easy, Medium, or Hard.")


def ask_companies() -> str:
    raw = input("Companies (comma-separated, or blank): ").strip()
    if not raw:
        return "TBD"
    parts = [part.strip() for part in raw.split(",") if part.strip()]
    return ", ".join(parts) if parts else "TBD"


def solution_template(method_name: str) -> str:
    return f"""class Solution:
    def {method_name}(self, *args):
        pass


# DEBUG RUNNER START
if __name__ == "__main__":
    print(Solution().{method_name}())
# DEBUG RUNNER END
"""


def sidecar_template(
    problem_number: str,
    problem_title: str,
    problem_slug: str,
    topic: str,
    difficulty: str,
    companies: str,
) -> str:
    return f"""# {problem_number}. {problem_title}

- **Difficulty:** {difficulty}
- **Pattern:** {topic}
- **Companies:** {companies}
- **Last reviewed:** {date.today().isoformat()}
- **LeetCode:** https://leetcode.com/problems/{problem_slug}/

> Company tags are a curated, approximate "frequently asked at" list and change
> over time. Treat them as prioritization hints, not authoritative data.

## Problem

_One or two line restatement of the problem._

## Approaches

### Brute force

_Describe the naive idea._

- Time: `O(?)`
- Space: `O(?)`

### Optimal

_Describe the intended pattern solution._

- Time: `O(?)`
- Space: `O(?)`

## Key insight

_The single idea that unlocks the optimal solution._

## Edge cases

- _e.g. empty input, single element, duplicates, overflow._

## Pitfalls

- _Common mistakes when implementing this._

## Related problems

- _Problems that use the same pattern._
"""


METADATA_PATTERN = re.compile(r"^- \*\*(?P<key>[^:*]+):\*\*\s*(?P<value>.*)$")


def read_metadata(sidecar: Path) -> dict[str, str]:
    metadata: dict[str, str] = {}
    if not sidecar.exists():
        return metadata
    for line in sidecar.read_text(encoding="utf-8").splitlines():
        match = METADATA_PATTERN.match(line.strip())
        if match:
            metadata[match.group("key").strip().lower()] = match.group("value").strip()
    return metadata


def _leading_number(stem: str) -> int:
    match = re.match(r"(\d+)", stem)
    return int(match.group(1)) if match else 10**9


def problem_files(folder: Path) -> list[Path]:
    return sorted(
        (path for path in folder.glob("*.py") if not path.name.startswith("00")),
        key=lambda path: (_leading_number(path.stem), path.stem),
    )


CHECKBOX_PATTERN = re.compile(r"- \[(?P<mark>[ xX])\].*?\((?P<rel>[^)]+\.py)\)")


def parse_checked(text: str) -> set[str]:
    checked: set[str] = set()
    for match in CHECKBOX_PATTERN.finditer(text):
        if match.group("mark").lower() == "x":
            checked.add(match.group("rel").replace("\\", "/"))
    return checked


def build_index(root: Path, checked: set[str] | None = None) -> str:
    checked = checked or set()
    lines: list[str] = []
    folders = topic_folders(root)

    total = 0
    counts: list[tuple[str, int]] = []
    for folder in folders:
        count = len(problem_files(folder))
        if count:
            counts.append((folder.name, count))
            total += count

    lines.append(f"**Total solved: {total} problems across {len(counts)} topics.**")
    lines.append("")
    lines.append("| Topic | Solved |")
    lines.append("| --- | ---: |")
    for name, count in counts:
        lines.append(f"| [{name}](#{name}) | {count} |")
    lines.append("")

    for folder in folders:
        files = problem_files(folder)
        if not files:
            continue
        lines.append(f"### {folder.name}")
        lines.append("")
        for path in files:
            metadata = read_metadata(path.with_suffix(".md"))
            difficulty = metadata.get("difficulty", "")
            companies = metadata.get("companies", "")
            number = _leading_number(path.stem)
            rel = f"{folder.name}/{path.name}"
            suffix_parts = [
                part for part in (difficulty, companies) if part and part != "TBD"
            ]
            suffix = f" · {' · '.join(suffix_parts)}" if suffix_parts else ""
            note = path.with_suffix(".md")
            title = f"[{path.stem}]({rel})"
            if note.exists():
                title += f" · [notes]({folder.name}/{note.name})"
            mark = "x" if rel in checked else " "
            lines.append(f"- [{mark}] **{number}** {title}{suffix}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def rebuild_readme_index(root: Path) -> None:
    readme = root / "README.md"

    if readme.exists():
        text = readme.read_text(encoding="utf-8")
    else:
        text = "# DSA Learning\n"

    checked = parse_checked(text)
    index_block = f"{INDEX_START}\n{build_index(root, checked)}{INDEX_END}"

    if INDEX_START in text and INDEX_END in text:
        start = text.index(INDEX_START)
        end = text.index(INDEX_END) + len(INDEX_END)
        text = text[:start] + index_block + text[end:]
    else:
        section = f"\n## Progress Tracker\n\n{index_block}\n"
        text = text.rstrip() + "\n" + section

    readme.write_text(text, encoding="utf-8")
    print("Updated README.md progress tracker.")


def report_progress(root: Path) -> None:
    readme = root / "README.md"
    checked = parse_checked(readme.read_text(encoding="utf-8")) if readme.exists() else set()

    done_total = 0
    all_total = 0
    for folder in topic_folders(root):
        files = problem_files(folder)
        if not files:
            continue
        done = sum(1 for path in files if f"{folder.name}/{path.name}" in checked)
        done_total += done
        all_total += len(files)
        bar_len = 20
        filled = round(bar_len * done / len(files)) if files else 0
        bar = "#" * filled + "-" * (bar_len - filled)
        print(f"{folder.name:<22} [{bar}] {done:>3}/{len(files)}")

    pct = (100 * done_total / all_total) if all_total else 0
    print("-" * 52)
    print(f"{'TOTAL':<22} {done_total}/{all_total} ({pct:.0f}%)")


def create_problem(root: Path) -> None:
    folders = topic_folders(root)
    if not folders:
        print("No topic folders found.")
        return

    folder = choose_folder(folders)
    problem_number = ask_problem_number()
    problem_title, problem_slug = ask_problem_title()
    method_name = ask_method_name()
    difficulty = ask_difficulty()
    companies = ask_companies()

    file_name = f"{problem_number}-{problem_slug}.py"
    path = folder / file_name
    sidecar = path.with_suffix(".md")

    if path.exists():
        print(f"{path} already exists. No file was created.")
        return

    path.write_text(solution_template(method_name), encoding="utf-8")
    print(f"Created {path}")

    if sidecar.exists():
        print(f"{sidecar} already exists. Skipped note.")
    else:
        sidecar.write_text(
            sidecar_template(
                problem_number,
                problem_title,
                problem_slug,
                folder.name,
                difficulty,
                companies,
            ),
            encoding="utf-8",
        )
        print(f"Created {sidecar}")

    rebuild_readme_index(root)


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold DSA solutions and notes.")
    parser.add_argument(
        "--reindex",
        action="store_true",
        help="Only rebuild the README progress tracker, then exit.",
    )
    parser.add_argument(
        "--progress",
        action="store_true",
        help="Print how many problems are checked off per topic, then exit.",
    )
    args = parser.parse_args()

    root = Path.cwd()
    if args.reindex:
        rebuild_readme_index(root)
        return

    if args.progress:
        report_progress(root)
        return

    create_problem(root)


if __name__ == "__main__":
    main()
